### ISSUE TITLE
body validation

### ISSUE THREAD

**Issue by alfayez91** [binitghetiya/express-sequelize-api-boilerplate#11]
how to modify the response to be a json formate instead of html formate in post request when validating using "express-validation"

**Comment by binitghetiya** [comment]
@alfayez91 can you please explain more because body validation + error throw both are working fine and sending JSON response only.
<img width="560" alt="Screen Shot 2021-04-21 at 4 12 36 PM" src="https://user-images.githubusercontent.com/14307119/115541200-78d97280-a2bc-11eb-9976-187218fd0c08.png">


<img width="811" alt="Screen Shot 2021-04-21 at 4 12 29 PM" src="https://user-images.githubusercontent.com/14307119/115541182-7414be80-a2bc-11eb-96fc-418547a862ca.png">

**Comment by alfayez91** [comment]
@binitghetiya sure please check the screenshot attached

<img width="1262" alt="Screen Shot 2021-04-21 at 1 50 16 PM" src="https://user-images.githubusercontent.com/37950083/115542459-f7c4b000-a2a8-11eb-8f9a-7ae5e8378609.png">

<img width="1129" alt="Screen Shot 2021-04-21 at 1 54 24 PM" src="https://user-images.githubusercontent.com/37950083/115542621-1f1b7d00-a2a9-11eb-81d6-4f00462460b4.png">

**Comment by binitghetiya** [comment]
Please try adding this and check.
<img width="647" alt="Screen Shot 2021-04-21 at 4 27 28 PM" src="https://user-images.githubusercontent.com/14307119/115542960-7841db80-a2be-11eb-8460-d50fbb9a72ad.png">

**Comment by binitghetiya** [comment]
Dear @alfayez91 , 
- Please check you are using the latest code from the repo
- update to latest package.json
- (if still issue persists) then try using the postman collection I have shared.

Just checked with **the new clone and it's working fine**.

**Comment by alfayez91** [comment]
Yes I have the latest code.
also the content-type is set as application/json

<img width="958" alt="Screen Shot 2021-04-21 at 2 03 04 PM" src="https://user-images.githubusercontent.com/37950083/115544518-60149100-a2ab-11eb-8e01-370f233ad436.png">

**Comment by binitghetiya** [comment]
As told you @alfayez91 I just did a new clone of the repo and seems working fine.

- src/middleware/errorHandler.js
- src/helpers/index.js

Please check both files are up to date with the current repo, if still in doubt you can get in touch with me on my personal email binitlearning@gmail.com

Closing this issue as working fine with new clone.
