### ISSUE TITLE
[Feature Request]: Add scripts for sequelize on package.json

### ISSUE THREAD

**Issue by shreyshreyansh** [binitghetiya/express-sequelize-api-boilerplate#32]
It will be intuitive to run a script from `package.json` rather than running below commands on terminal
> node_modules/.bin/sequelize db:migrate
> node_modules/.bin/sequelize db:seed:all

We can add scripts to `package.json`
```
"migration:generate": "npx sequelize-cli migration:create --name"
```
And then we can simply run `npm run migration:generate xxx`

It will be more expressive and easy to understand

**Comment by binitghetiya** [comment]
Hey

Good thought, you can open PR if you want.
I will review and merge
